### PR TITLE
Add literacy support to WFRP4e

### PR DESCRIPTION
**Pull request by patengelbert**
The WFRP4e system has literacy in the form of the Read/Write talent, which allows reading/writing of all languages that the character knows.

This PR adds support to Polyglot in the same manner as other game systems.

### CODE REVIEW

**Comment by RavenknightDM** [comment]
It doesn't seem to work for my game. Is there any additional steps besides the characters having the Read/Write Talent that I should take?

**Comment by patengelbert** [comment]
@RavenknightDM, it is broken for me. It appears that there was this change 033663543206122aeba09ad2fe4a94ff2ecb8218 which replaced the `items.filter` with `items.find`, which in turn causes all checks for `.length` to fail as no array is returned. I will create a fix.

For the second issue: `And un-scrambled if its in the inventory even if the character doesn't have the language and the trait` This is due to the character being treated as the owner of the document, in which case it is never scrambled and would require changes to the core of polyglot.

**Comment by RavenknightDM** [comment]
Hiya, thanks for the answer and the inclusion of Read/Write. :) I was uncertain if things was unscrambled or not in inventory. Good to know. I mostly use Polyglot for ancient texts upon plaques and stuff.

**Comment by patengelbert** [comment]
The fix is here https://github.com/mclemente/fvtt-module-polyglot/pull/389.

As a workaround for "owned" items being translated, you can give the character an item with a link to the global item/journal. This way it is not considered owned by FoundryVTT and therefor, it will not be unscrambled automatically

**Pull request merged**
